AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  climbing-charts

  Make charts of the capacity of climbing walls in London over time

Globals:
  Function:
    Timeout: 30
  Api:
    Cors:
      AllowOrigin: "'*'"

Resources:
  ClimbingScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: climbing-scrape/
      Handler: app.scrape_walls
      Runtime: python3.8
      Description: Scrape capacity info from the Lakeland Climbing Centre walls and stash it in DynamoDB
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSXRayDaemonWriteAccess
      Tracing: Active
      Events:
        EveryFiveMinutes:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Name: every-five-minutes
            Description: I mean, you run the thing every five minutes, how hard is it
            Enabled: True

  ClimbingDisplayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: climbing-scrape/
      Handler: app.load_from_dynamo
      Runtime: python3.8
      Description: Load and print scraped capacity info
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSXRayDaemonWriteAccess
      Tracing: Active
      Events:
        DisplayClimbingCapacity:
          Type: Api
          Properties:
            Path: /
            Method: get

  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: timestamp
        Type: Number
      TableName: climbing-capacity-info

Outputs:
  ClimbingScraperFunction:
    Description: "ClimbingScraperFunction Function ARN"
    Value: !GetAtt ClimbingScraperFunction.Arn
  SillyFunctionIamRole:
    Description: "Implicit IAM Role created for my function"
    Value: !GetAtt ClimbingScraperFunctionRole.Arn
  DynamoDBTable:
    Description: "I don't know what I'm doing this is a dynamodb table"
    Value: !GetAtt DynamoDBTable.Arn
  DisplayClimbingCapacityApi:
    Description: "API Gateway endpoint URL for Prod stage for display function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
