AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  climbing-charts

  Sample SAM Template for climbing-charts

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  ClimbingScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: climbing-scrape/
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: Scrape capacity info from the Lakeland Climbing Centre walls and stash it in DynamoDB
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSXRayDaemonWriteAccess
      Tracing: Active
      Events:
        EveryFiveMinutes:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Name: every-five-minutes
            Description: I mean, you run the thing every five minutes, how hard is it
            Enabled: True

  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: timestamp
        Type: Number
      TableName: climbing-capacity-info

Outputs:
  ClimbingScraperFunction:
    Description: "ClimbingScraperFunction Function ARN"
    Value: !GetAtt ClimbingScraperFunction.Arn
  SillyFunctionIamRole:
    Description: "Implicit IAM Role created for my function"
    Value: !GetAtt ClimbingScraperFunctionRole.Arn
  DynamoDBTable:
    Description: "I don't know what I'm doing this is a dynamodb table"
    Value: !GetAtt DynamoDBTable.Arn
